version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-9000}:9000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "./scripts/wait-for-db.sh db && npm run dev"

  db:
    image: postgres:15-alpine
    ports:
      - "${DB_PORT:-5432}:5432"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 